### PR TITLE
fix abuse

### PR DESCRIPTION
**Pull request by AlfieC**

### CODE REVIEW

**Comment by hawkfalcon** [comment]
What are you expecting this to do?

**Comment by AlfieC** [comment]
...fix (some) static abuse?

**Comment by frostalf** [comment]
There is no benefit from changing it to non-static other than reducing 1 import line.

**Comment by AlfieC** [comment]
This one doesn't hurt my eyes as much - and isn't (as) shit code.

**Comment by frostalf** [comment]
Closed for not being beneficial. You can improve your PR by either including fixes or possible additions and documenting documenting what the purpose of the PR is for. If your PR is for the purpose of code beautification, then it should be more than a couple lines changed.

**Comment by AlfieC** [comment]
I'll fix the entire code base for you then. Will PR shortly.

**Comment by frostalf** [comment]
While you have a belief that statics are bad, which they are not, they do have their place. This plugin does have a few areas where statics are indeed needed. Also know that, not dereferencing Bukkit as a static, doesn't make Bukkit go away either as there will always be an instance of Bukkit regardless. Which is the reason I said there was no benefit of either referencing Bukkit statically or non-statically.

**Pull request closed without merging**
